### PR TITLE
Major refactor - migrating CALM to a specific JSON vocabulary

### PR DESCRIPTION
**Pull request by rocketstack-matt**
Adding a new JSON Schema Vocab and switching to being meta schema based to provide better autocompletion and validation capabilities.

### CODE REVIEW

**Comment by jpgough-ms** [comment]
Will resolve #11

**Comment by rocketstack-matt** [comment]
Good point, I wasn't thinking I've just been so deep in understanding how to write json vocabs and meta-schemas :D 

Will re-add.

**Comment by rocketstack-matt** [comment]
@Budlee  see https://github.com/finos-labs/architecture-as-code/pull/22

**Comment by Budlee** [comment]
@jpgough-ms  and @rocketstack-matt , again this goes back to my question in issue#10 (https://github.com/finos-labs/architecture-as-code/issues/10)

In the api-gateway-implementation you are using Interacts as the relationship type instead of connects. Yet in TraderX we use interacts for Actors to Nodes and not for Services connecting. This goes to the point I made in the issue where we  have equivalent types of relationship types that not not strongly defined.

I think these need to be defined or at least documented which each one is

**Comment by jpgough-ms** [comment]
@jpgough-ms this is my error, whilst looking at the schema for the first time.

In addition this is something that we can look to add into the ruleset for #20

**Comment by rocketstack-matt** [comment]
Have merged this

**Pull request merged**
