### PR TITLE
Configure semgrep

### LINKED ISSUE #148: Setup Static Code Analysis
### Description of Problem:
Whilst we already have GitHub CodeQL setup, we need to add Semgrep to be able to migrate to the FINOS GitHub org.

### Potential Solutions:
Detailed instructions to setup Semgrep [here](https://github.com/finos/code-scanning/blob/main/README.md#static-code-analysis)

### PR DESCRIPTION
**Pull request by rocketstack-matt**
@TheJuanAndOnly99 this PR should be merged once the SEMGREP_APP_TOKEN secret has been added.

Resolves #148

### CODE REVIEW

**Comment by TheJuanAndOnly99** [comment]
@rocketstack-matt The SEMGREP_APP_TOKEN secret has been added!

**Comment by rocketstack-matt** [comment]
@TheJuanAndOnly99 the action has run (see [here](https://github.com/finos-labs/architecture-as-code/actions/runs/8787719344/job/24113854420) but you can see under the "Run semgrep ci" step

```shell
run `semgrep login` before using `semgrep ci` or use `semgrep scan` and set `--config`
There were errors during analysis but Semgrep will succeed because there were no blocking findings, use --no-suppress-errors if you want Semgrep to fail when there are errors.
```

I am able to run the scan locally and don't see anything explicitly calling login or the `semgrep scan --error --config auto` command in the action itself. 

Am I missing something or is this perhaps because this project is currently in the finos-labs rather than finos GitHub org?

**Comment by maoo** [comment]
@rocketstack-matt - Github actions running on PRs normally don't have access to secrets, for security reasons; you may have to merge the PR to see it in action.

**Comment by rocketstack-matt** [comment]
Thanks @maoo will give that a try - tbh I was surprised that it ran as normally actions run in the forked repo, anyway let see.

**Pull request merged**
